[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwasm = "0.4.0"
serde = { version = "1.0.133", features = ["derive"] }
wasm-bindgen-futures = "0.4.28"
yew = "0.19.3"
